# Nixpacks Configuration
# This file tells Railway to NOT use Nixpacks/Railpack
# Use Dockerfile instead

[phases.build]
cmds = ["echo 'Please use Dockerfile builder'"]

[phases.install]
cmds = ["echo 'This project requires Docker'"]

