# TrendXL 2.0 - Railway Configuration for Fullstack Application
# Single service that combines React/Vite frontend with Python FastAPI backend

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/start-services.sh"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT, but we can define defaults
NODE_ENV = "production"
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
HOST = "0.0.0.0"
DEBUG = "false"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"