# Railway Configuration для TrendXL 2.0

# Backend Service
[[services]]
name = "backend"
root = "backend"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 30

# Frontend Service
[[services]]
name = "frontend"
root = "."

[services.healthcheck]
path = "/health"
timeout = 30
interval = 30

