# TrendXL 2.0 - Railway Backend Service Configuration
# Python FastAPI Backend Service

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"
# Watch only backend-related files to avoid unnecessary rebuilds
watchPatterns = ["/backend/**"]

[deploy]
startCommand = "python run_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Graceful shutdown configuration
numReplicas = 1
overlapSeconds = 30
drainingSeconds = 60

[env]
# Python environment
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Server configuration
HOST = "0.0.0.0"
DEBUG = "false"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# API Keys (set these in Railway UI as secrets)
# ENSEMBLE_API_TOKEN = (set in Railway UI)
# OPENAI_API_KEY = (set in Railway UI)
# PERPLEXITY_API_KEY = (set in Railway UI - optional)

# Redis configuration (if using Railway Redis service)
# REDIS_URL = "${{Redis.REDIS_URL}}"

# Database configuration (if using Railway Postgres service)
# DATABASE_URL = "${{Postgres.DATABASE_URL}}"
