# TrendXL 2.0 - Railway Multi-Service Configuration
# 
# ⚠️ ВАЖНО: Railway автоматически обрабатывает маршрутизацию между сервисами!
# 
# Этот файл НЕ используется для настройки роутинга.
# Маршрутизация работает автоматически через Railway переменные:
#   - ${{Backend.RAILWAY_PUBLIC_DOMAIN}}
#   - ${{Frontend.RAILWAY_PUBLIC_DOMAIN}}
#
# ПРАВИЛЬНЫЙ СПОСОБ ДЕПЛОЯ на Railway:
# 1. Создать Backend Service через Railway UI
#    - Settings → Build → Dockerfile Path: Dockerfile.backend
#    - Variables → указать API ключи
#    - Networking → Generate Domain
#
# 2. Создать Frontend Service через Railway UI
#    - Settings → Build → Dockerfile Path: Dockerfile.frontend
#    - Variables → VITE_BACKEND_API_URL=https://${{Backend.RAILWAY_PUBLIC_DOMAIN}}
#    - Networking → Generate Domain
#
# Railway автоматически:
#   ✅ Создаст внутреннюю сеть между сервисами
#   ✅ Назначит динамические порты через ${{RAILWAY_PORT}}
#   ✅ Настроит HTTPS и SSL сертификаты
#   ✅ Обеспечит связь Frontend ↔ Backend
#
# Подробнее: RAILWAY_DEPLOYMENT_GUIDE.md
#
# -------------------------------------------------------------------
# Ниже представлена справочная конфигурация для отдельных сервисов
# (используйте railway.backend.json и railway.frontend.json вместо этого файла)
# -------------------------------------------------------------------