# Railway Backend Service Configuration
# For standalone Python FastAPI backend

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python run_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

