# TrendXL 2.0 - Railway Configuration for Backend Service
# Standalone Python FastAPI backend (no frontend, no nginx)

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python run_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT, but we can define defaults
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
HOST = "0.0.0.0"
DEBUG = "false"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"