# TrendXL 2.0 - DEPRECATED Railway Configuration
# ⚠️ This file is for SINGLE backend-only deployment
# 
# For SEPARATE backend + frontend services deployment, use:
#   - railway.backend.toml (for backend service)
#   - railway.frontend.toml (for frontend service)
#
# See RAILWAY_DEPLOYMENT_GUIDE_V2.md for full instructions
#
# This file kept for backward compatibility with single-service deployments

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python run_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT, but we can define defaults
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
HOST = "0.0.0.0"
DEBUG = "false"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"