# TrendXL 2.0 - Railway Frontend Service Configuration
# React + Vite Frontend served by Nginx

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.frontend"
# Watch only frontend-related files to avoid unnecessary rebuilds
watchPatterns = [
    "/src/**",
    "/public/**",
    "/index.html",
    "/package.json",
    "/package-lock.json",
    "/vite.config.ts",
    "/tsconfig.json",
    "/tailwind.config.js",
    "/postcss.config.js",
    "/nginx.conf",
    "/.env.production"
]

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Nginx can start quickly, minimal overlap needed
numReplicas = 1
overlapSeconds = 10
drainingSeconds = 30

[env]
# Backend API URL - reference the backend service
# Set this to your backend service's public domain in Railway UI
# Example: VITE_BACKEND_API_URL = "https://${{Backend.RAILWAY_PUBLIC_DOMAIN}}"
# Or manually: VITE_BACKEND_API_URL = "https://your-backend-service.up.railway.app"

# Note: VITE_ prefixed variables must be set at BUILD time
# They are baked into the JavaScript bundle during npm run build
# Railway will automatically use these during the Docker build process
